// Automatically generated by scripts/extract-enums.js

export const BOOKING_STATUS = [
  "pending",
  "confirmed",
  "ongoing",
  "completed",
  "cancelled",
] as const;

export type BookingStatus = (typeof BOOKING_STATUS)[number];

export const FUEL_TYPE = [
  "Petrol",
  "Diesel",
  "Electric",
  "Hybrid",
] as const;

export type FuelType = (typeof FUEL_TYPE)[number];

export const RESERVATION_STATUS = [
  "ongoing",
  "cancelled",
  "completed",
] as const;

export type ReservationStatus = (typeof RESERVATION_STATUS)[number];

export const TRANSMISSION_TYPE = [
  "Auto",
  "Manual",
] as const;

export type TransmissionType = (typeof TRANSMISSION_TYPE)[number];

export const USER_ROLE = [
  "admin",
  "manager",
  "support",
  "user",
] as const;

export type UserRole = (typeof USER_ROLE)[number];

export const USER_STATUS = [
  "active",
  "suspended",
] as const;

export type UserStatus = (typeof USER_STATUS)[number];

export const VEHICLE_APPROVAL = [
  "approved",
  "pending",
  "rejected",
] as const;

export type VehicleApproval = (typeof VEHICLE_APPROVAL)[number];

export const VEHICLE_STATUS = [
  "available",
  "unavailable",
] as const;

export type VehicleStatus = (typeof VEHICLE_STATUS)[number];

export const VEHICLE_TYPE = [
  "Sedan",
  "SUV",
  "Coupe",
  "Hatchback",
  "Convertible",
  "Wagon",
  "Van",
  "Pickup",
  "Sports Car",
  "Luxury",
  "Electric",
  "Hybrid",
] as const;

export type VehicleType = (typeof VEHICLE_TYPE)[number];

