/* eslint-disable @typescript-eslint/no-require-imports */
const fs = require("fs");
const path = require("path");

const typesFilePath = path.join(__dirname, "../src/db/database.types.ts");
const enumsFilePath = path.join(__dirname, "../src/db/enums.ts");

if (!fs.existsSync(typesFilePath)) {
  console.error("database.types.ts not found. Please run gen-types first.");
  process.exit(1);
}

const content = fs.readFileSync(typesFilePath, "utf8");

function pascalCaseFromSnake(name) {
  return name
    .split("_")
    .filter(Boolean)
    .map((p) => p.charAt(0).toUpperCase() + p.slice(1))
    .join("");
}

// We look for the Enums block inside public. Keep it resilient to multiline unions.
const enumsMatch = content.match(/Enums:\s*{([\s\S]*?)^\s*}\s*^\s*CompositeTypes:/m);

if (!enumsMatch) {
  console.log("No Enums found in database.types.ts");
  process.exit(0);
}

const enumsBlock = enumsMatch[1];
const enumLines = enumsBlock.split("\n").map(l => l.trim()).filter(l => l);

const enums = {};
let currentEnum = null;

for (const line of enumLines) {
  // Check if it's an enum start, e.g., "booking_status:"
  // Or "reservation_status: "ongoing" | "cancelled""
  const startMatch = line.match(/^([a-zA-Z0-9_]+):(.*)$/);
  
  if (startMatch) {
    currentEnum = startMatch[1];
    enums[currentEnum] = [];
    const rest = startMatch[2].trim();
    if (rest) {
      // Inline values like: "ongoing" | "cancelled" | "completed"
      const values = rest.split("|").map(v => v.trim().replace(/"/g, "")).filter(v => v);
      enums[currentEnum].push(...values);
    }
  } else if (currentEnum) {
    // Continuation of values like: | "pending"
    const valMatch = line.match(/\|\s*"([^"]+)"/);
    if (valMatch) {
      enums[currentEnum].push(valMatch[1]);
    }
  }
}

let output = "// Automatically generated by scripts/extract-enums.js\n\n";

for (const [enumName, values] of Object.entries(enums)) {
  output += `export const ${enumName.toUpperCase()} = [\n`;
  for (const val of values) {
    output += `  "${val}",\n`;
  }
  output += `] as const;\n\n`;
  
  output += `export type ${pascalCaseFromSnake(enumName)} = (typeof ${enumName.toUpperCase()})[number];\n\n`;
}

fs.writeFileSync(enumsFilePath, output);
console.log("Successfully extracted enums to src/db/enums.ts");
